New color system to support Python 3!
Now supports python 3.
Added:
New Welcome message on import.
Errors:
Error: Mu crashes on import.
Cause: Mu doesn't support text color.